spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:chatty-postgres}:${DB_PORT:5432}/${DB_NAME:chattybase}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}

llm:
  api:
    key: ${LLM_API_KEY}
    base-url: ${LLM_API_BASE_URL:https://api.groq.com/openai/v1}
  model: ${LLM_MODEL:llama-3.1-8b-instant}